accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup', views.signup_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

articles/urls.py
from django.urls import path, include
from . import views

app_name = "articles"
urlpatterns = [
    path('', views.article_list, name="list"),
    path('<slug>', views.article_detail, name="detail"),
]

famemo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('', views.home),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

post/urls.py
from django.urls import path
from . import views


app_name = 'post'
urlpatterns = [
    path('add_post/', views.add_post, name='add_post'),
]

articles/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

    def get_absolute_url(self):
        return reverse({'article': list})

post/forms.py
from django import forms
from . import models


class Create_post(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'slug', 'body']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, HttpResponse
from . import models
# Create your views here.


def article_list(request):
    articles = models.Article.objects.all().order_by('date')
    return render(request, 'articles/articleslist.html', {'articles': articles})


def article_detail(request, slug):
    # return HttpResponse(slug)
    article = models.Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

famemo/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse


def about(request):
    # return HttpResponse("Hi! this is one TEST")
    return render(request, 'about.html')


def home(request):
    # return HttpResponse("HOME")
    return render(request, 'home.html')

post/views.py
from django.shortcuts import render, HttpResponse, redirect
from . import models
from django.contrib.auth.decorators import login_required
from . import forms
from articles import urls
# Create your views here.


@login_required(login_url="/accounts/login")
def add_post(request):
    if request.method == 'POST':
        form = forms.Create_post(request.POST)
        if form.is_valid():
            return redirect('articles:list')
    else:
        form = forms.Create_post()
    return render(request, 'post_visit/add_post.html', {'form': form})

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content%}
<h1> Login </h1>

<form class="" action="/accounts/login" method="POST">
    {{form}}
    {% csrf_token %}

    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">

    {% endif %}
    <input type="submit" value="login">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content%}
<h1> Signup </h1>

<form class="site_form" action="/accounts/signup" method="POST">
    {{form}}
    {% csrf_token %}
    <input type="submit" value="submit">
</form>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base.html' %}
{% block content%}
<div class="article-detail">
    <div class="artcle">
        <h1>{{article.title}}</h1>
        <p>{{article.body}}</p>
        <p>{{article.date}}</p>
    </div>

</div>
{% endblock %}

articles/templates/articles/articleslist.html
{% extends 'base.html' %}
{% block title%}
ARTICLES
{% endblock%}
{% block content%}
<div class="container">
    <h1> Articles List </h1>
    {% for ithem in articles %}
    <h2><a href="{% url 'articles:detail' slug=ithem.slug %}">{{ithem.title}}</a></h2>
    <p>{{ithem.snippet}}</p>
    <P>{{ithem.date}}</P>
    {% endfor %}
</div>
{% endblock %}

famemo/templates/about.html
<html lang="en" , dir="rtl">

<head>
    <title>ABOUT</title>
</head>

<body>
    <h1>ABOUT </h1>
    <P> جایی برای متن های شما</P>
</body>

</html>

famemo/templates/base.html
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title%}
        {% endblock%}
    </title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
    <h2><a href="{% url 'articles:list'%}">FAMEMO</a></h2>
    <nav>
        <ul>
            <li>
                <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">logout</button>

                </form>
            </li>
        </ul>
    </nav>
    <div class="wrapper">
        {% block content%}
        {% endblock %}
    </div>
</body>

</html>

famemo/templates/home.html
<html>

<head>
    <meta charset="utf-8">
    <title>HOME</title>
</head>

<body>
    <h1> HOME </h1>
    <P>welcome to FAMEMO</P>
</body>

</html>

post/templates/post_visit/add_post.html
{% extends 'base.html' %}
{% block content%}
<div class="add-post">
    <h1> Add Post </h1>
    <form class="site-form" action="{% url 'post:add_post' %}" method="POST">
        {{form}}
        {% csrf_token %}
        <input type="submit" value="Add">
    </form>
</div>

{% endblock %}